package com.teslenko.operators;

public class E12_UnsignedRightShift {
    public static void main(String[] args) {
        int i = -1;
        System.out.println(Integer.toBinaryString(i));
        i <<= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
        i >>>= 1;
        System.out.println(Integer.toBinaryString(i));
    }
}
